# ADP-OS CLI parameter contract checks
# Guards against command switches being accepted but not propagated.

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path $PSScriptRoot -Parent

function Read-Text {
    param([string]$RelativePath)
    return Get-Content -LiteralPath (Join-Path $projectRoot $RelativePath) -Raw
}

function Assert-Contains {
    param(
        [string]$Name,
        [string]$Text,
        [string]$Pattern
    )

    if ($Text -notmatch $Pattern) {
        throw "$Name did not contain expected pattern: $Pattern"
    }
}

$up = Read-Text "cli\commands\up.ps1"
$init = Read-Text "cli\commands\init.ps1"
$install = Read-Text "install.ps1"
$factory = Read-Text "runtimes\vmware\vm-factory.ps1"
$cli = Read-Text "cli\adp.ps1"
$logger = Read-Text "core\logging\logger.ps1"
$logs = Read-Text "cli\commands\logs.ps1"
$sync = Read-Text "cli\commands\sync.ps1"
$network = Read-Text "cli\commands\network.ps1"
$doctor = Read-Text "cli\commands\doctor.ps1"
$workspace = Read-Text "cli\commands\workspace.ps1"
$ci = Read-Text ".github\workflows\ci.yml"
$validate = Read-Text "tests\validate.ps1"
$networkingDocs = Read-Text "docs\networking.md"
$networkingDocsZh = Read-Text "docs\zh-CN\networking.md"
$workspaceDocs = Read-Text "docs\workspaces.md"
$workspaceDocsZh = Read-Text "docs\zh-CN\workspaces.md"
$capabilitiesDocs = Read-Text "docs\capabilities.md"
$capabilitiesDocsZh = Read-Text "docs\zh-CN\capabilities.md"
$roadmapDocs = Read-Text "docs\roadmap.md"
$roadmapDocsZh = Read-Text "docs\zh-CN\roadmap.md"
$troubleshootingDocs = Read-Text "docs\troubleshooting.md"
$troubleshootingDocsZh = Read-Text "docs\zh-CN\troubleshooting.md"
$releaseReadinessDocs = Read-Text "docs\release-readiness.md"
$releaseReadinessDocsZh = Read-Text "docs\zh-CN\release-readiness.md"
$releaseProcessDocs = Read-Text "docs\release-process.md"
$releaseProcessDocsZh = Read-Text "docs\zh-CN\release-process.md"
$contributorWorkflowDocs = Read-Text "docs\contributor-workflows.md"
$contributorWorkflowDocsZh = Read-Text "docs\zh-CN\contributor-workflows.md"
$pullRequestTemplate = Read-Text ".github\pull_request_template.md"

Assert-Contains -Name "CLI help defined before use" -Text $cli -Pattern 'function\s+Show-Help[\s\S]*if\s*\(-not\s+\$Command\s+-or\s+\$Command\s+-eq\s+"help"\)'
Assert-Contains -Name "CLI propagates command exit codes" -Text $cli -Pattern 'Invoke-CommandFile[\s\S]*if\s*\(\$LASTEXITCODE\)\s*\{[\s\S]*exit\s+\$LASTEXITCODE'
Assert-Contains -Name "CI runs shared validation entry" -Text $ci -Pattern '\.\\tests\\validate\.ps1'
Assert-Contains -Name "shared validation runs installer smoke tests" -Text $validate -Pattern '\.\\tests\\install-smoke\.ps1'
Assert-Contains -Name "shared validation runs CLI smoke tests" -Text $validate -Pattern '\.\\tests\\cli-smoke\.ps1'
Assert-Contains -Name "shared validation runs documentation language link checks" -Text $validate -Pattern '\.\\tests\\docs-language-links\.ps1'
Assert-Contains -Name "shared validation runs configuration schema checks" -Text $validate -Pattern '\.\\tests\\config-schema\.ps1'
Assert-Contains -Name "shared validation runs artifact hygiene checks" -Text $validate -Pattern '\.\\tests\\artifact-hygiene\.ps1'
Assert-Contains -Name "documentation language checks enforce translated doc pairs" -Text (Read-Text "tests\docs-language-links.ps1") -Pattern 'Assert-TranslatedDocPair[\s\S]*README[\s\S]*CHANGELOG[\s\S]*build[\s\S]*docs/zh-CN'
Assert-Contains -Name "shared validation parses workspace recipes example" -Text $validate -Pattern 'configs\\workspace\.recipes\.example\.json'
Assert-Contains -Name "shared validation checks Markdown links" -Text $validate -Pattern 'Check Markdown local links'
Assert-Contains -Name "artifact hygiene ignores local assistant settings" -Text (Read-Text ".gitignore") -Pattern '(?m)^\.claude/[\s\S]*(?m)^\.codex/'
Assert-Contains -Name "artifact hygiene covers snapshot state and Windows NUL" -Text (Read-Text "tests\artifact-hygiene.ps1") -Pattern 'snapshots/[\s\S]*NUL'
Assert-Contains -Name "contributing shell syntax docs include common bootstrap script" -Text (Read-Text "CONTRIBUTING.md") -Pattern 'bootstrap/common/common\.sh'
Assert-Contains -Name "Chinese contributing shell syntax docs include common bootstrap script" -Text (Read-Text "CONTRIBUTING.zh-CN.md") -Pattern 'bootstrap/common/common\.sh'
Assert-Contains -Name "troubleshooting validation scope includes artifact hygiene" -Text $troubleshootingDocs -Pattern 'Repository validation fails[\s\S]*artifact hygiene'
Assert-Contains -Name "Chinese troubleshooting validation scope includes artifact hygiene" -Text $troubleshootingDocsZh -Pattern '仓库验证失败[\s\S]*artifact hygiene'
Assert-Contains -Name "shared validation supports quick local validation" -Text $validate -Pattern '\[switch\]\$Quick[\s\S]*if\s*\(\$Quick\)[\s\S]*\$SkipCliSmoke\s*=\s*\$true[\s\S]*\$SkipInstallerSmoke\s*=\s*\$true'
Assert-Contains -Name "shared validation supports local skip switches" -Text $validate -Pattern '\[switch\]\$SkipCliSmoke[\s\S]*\[switch\]\$SkipInstallerSmoke[\s\S]*\[switch\]\$SkipShellSyntax'
Assert-Contains -Name "CLI registers workspace command" -Text $cli -Pattern '\$validCommands\s*=\s*@\([\s\S]*"workspace"'
Assert-Contains -Name "CLI registers status command" -Text $cli -Pattern '\$validCommands\s*=\s*@\([\s\S]*"status"'
Assert-Contains -Name "CLI registers capabilities command" -Text $cli -Pattern '\$validCommands\s*=\s*@\([\s\S]*"capabilities"'
Assert-Contains -Name "CLI help includes status command" -Text $cli -Pattern 'adp status \[runtime\]'
Assert-Contains -Name "CLI help includes workspace command" -Text $cli -Pattern 'adp workspace <init\|show\|plan\|status\|dashboard\|report\|recipes\|create\|open\|sync\|project\|task>'
Assert-Contains -Name "CLI help includes capabilities command" -Text $cli -Pattern 'adp capabilities\s+Show supported and planned runtime capabilities'
Assert-Contains -Name "capabilities command documents supported and planned carriers" -Text (Read-Text "cli\commands\capabilities.ps1") -Pattern 'Capabilities only: no VMs[\s\S]*\[supported\] vmware-workstation[\s\S]*\[planned\] hyper-v[\s\S]*\[planned\] kvm-libvirt[\s\S]*\[planned\] macos-vm[\s\S]*Docker and dev containers are runtime-internal project tools today'
Assert-Contains -Name "capabilities docs define support boundary" -Text $capabilitiesDocs -Pattern '## Runtime Carrier Matrix[\s\S]*VMware Workstation[\s\S]*Supported on Windows[\s\S]*Hyper-V[\s\S]*Not implemented[\s\S]*Docker and dev containers are runtime-internal project tools today'
Assert-Contains -Name "Chinese capabilities docs define support boundary" -Text $capabilitiesDocsZh -Pattern '## 运行时承载矩阵[\s\S]*VMware Workstation[\s\S]*Windows 上已支持[\s\S]*Hyper-V[\s\S]*尚未实现[\s\S]*Docker 和 dev containers 当前是 runtime 内部项目工具'
Assert-Contains -Name "roadmap separates current workspace surface from remaining directions" -Text $roadmapDocs -Pattern '## Workspace Orchestration[\s\S]*Current public surface:[\s\S]*workspace create \[-Plan\][\s\S]*workspace open[\s\S]*workspace sync[\s\S]*workspace project[\s\S]*workspace report -Markdown[\s\S]*Remaining directions:[\s\S]*safer clone/import guidance'
Assert-Contains -Name "Chinese roadmap separates current workspace surface from remaining directions" -Text $roadmapDocsZh -Pattern '## 工作区编排[\s\S]*当前公开能力：[\s\S]*workspace create \[-Plan\][\s\S]*workspace open[\s\S]*workspace sync[\s\S]*workspace project[\s\S]*workspace report -Markdown[\s\S]*剩余方向：[\s\S]*clone/import guidance'
Assert-Contains -Name "roadmap separates current agent-native surface from broad execution direction" -Text $roadmapDocs -Pattern '## Agent-Native Development[\s\S]*Current public surface:[\s\S]*Task lifecycle commands[\s\S]*checkpoint-waived[\s\S]*Milestone and evaluation planning surfaces[\s\S]*Remaining directions:[\s\S]*Keep broad task execution plan-only'
Assert-Contains -Name "Chinese roadmap separates current agent-native surface from broad execution direction" -Text $roadmapDocsZh -Pattern '## Agent 原生开发[\s\S]*当前公开能力：[\s\S]*Task lifecycle commands[\s\S]*checkpoint-waived[\s\S]*Milestone 和 evaluation planning surfaces[\s\S]*剩余方向：[\s\S]*broad task execution 保持 plan-only'
Assert-Contains -Name "up -IsoPath propagation" -Text $up -Pattern 'New-RuntimeVM[\s\S]*-IsoPath\s+\$IsoPath'
Assert-Contains -Name "vm factory IsoPath parameter" -Text $factory -Pattern 'function\s+New-RuntimeVM[\s\S]*\[string\]\$IsoPath'
Assert-Contains -Name "vm factory IsoPath resolution" -Text $factory -Pattern '\$resolvedIsoPath\s*=\s*if\s*\(\$IsoPath\)'
Assert-Contains -Name "up prints connection summary" -Text $up -Pattern 'function\s+Write-RuntimeConnectionSummary[\s\S]*Connection details:[\s\S]*adp status \$TargetRuntime'
Assert-Contains -Name "up provisioning wait passes runtime" -Text $up -Pattern 'Wait-AutoinstallComplete\s+-VmxPath\s+\$TargetVmxPath\s+-RuntimeName\s+\$TargetRuntime'
Assert-Contains -Name "vm factory provisioning prefers configured static IP" -Text $factory -Pattern 'function\s+Wait-AutoinstallComplete[\s\S]*Get-RuntimeStaticIP\s+\$RuntimeName[\s\S]*configured.*\$ip'
Assert-Contains -Name "vm factory explains long autoinstall wait" -Text $factory -Pattern 'real guest OS installation[\s\S]*Typical duration: 15-45 minutes[\s\S]*Installing Ubuntu inside VM \(watched wait, not stuck; repeated signals can be normal\)[\s\S]*Install monitor active: INSTALLING Ubuntu in the VM[\s\S]*Watch path: installer boot -> OS install -> reboot -> SSH auth-pending -> provision marker -> bootstrap'
Assert-Contains -Name "vm factory reports autoinstall progress instead of vague waiting" -Text $factory -Pattern '\[install monitor\] INSTALLING Ubuntu in VM - watched wait, not stuck[\s\S]*status: state=installing activity=installing-ubuntu status=watching current-op=readiness-check wait-mode=watched progress=indeterminate user-action=keep-open diagnostics=vmware-console-after-20min phase=ubuntu-autoinstall[\s\S]*time: expected=15-45min timeout=\$\{TimeoutMinutes\}min[\s\S]*meaning: Ubuntu is still installing, rebooting, or preparing the installed-system user[\s\S]*readiness signals:[\s\S]*next: ADP will recheck readiness[\s\S]*action:[\s\S]*Autoinstall confirmation timed out'
Assert-Contains -Name "vm factory avoids fake autoinstall percentages" -Text $factory -Pattern 'Progress model: indeterminate OS install; VMware does not expose a reliable Ubuntu install percentage, so ADP reports real readiness signals'
Assert-Contains -Name "vm factory explains probes as readiness signals" -Text $factory -Pattern 'Readiness signals checked every \$\{CheckIntervalSeconds\}s[\s\S]*IP and SSH probe failures are readiness signals during install; they are not the primary status while the headline says INSTALLING'
Assert-Contains -Name "vm factory tells users when action is needed" -Text $factory -Pattern 'Normal during install: the same signal can repeat[\s\S]*User action: keep this command running[\s\S]*\[install monitor\] INSTALLING Ubuntu in VM - heartbeat active, repeated signal is normal[\s\S]*normal=yes[\s\S]*unchanged readiness signals are normal[\s\S]*same signal has repeated for about \$\{sameMinutes\}min; keep the command running'
Assert-Contains -Name "vm factory reports auth-pending as install readiness state" -Text $factory -Pattern 'auth-pending; SSH is up but installed-system user/key or provision marker is not ready'
Assert-Contains -Name "vm factory avoids long blocking IP probes during autoinstall monitor" -Text $factory -Pattern 'Get-VMIPQuick\s+-VmxPath\s+\$VmxPath\s+-TimeoutSeconds\s+5'
Assert-Contains -Name "vm factory readiness checks configured static IP" -Text $factory -Pattern 'function\s+Test-AutoinstallReady[\s\S]*Get-RuntimeStaticIP\s+\$RuntimeName[\s\S]*candidateIps'
Assert-Contains -Name "init -SkipProvision propagation" -Text $init -Pattern 'NoProvision\s*=\s*\$SkipProvision'
Assert-Contains -Name "init invokes up in shared script scope" -Text $init -Pattern '\.\s+\$upCommand\s+@upArgs'
Assert-Contains -Name "up -NoProvision skips bootstrap after creation" -Text $up -Pattern 'if\s*\(\$NoProvision\)\s*\{[\s\S]*bootstrap were skipped[\s\S]*return'
Assert-Contains -Name "install -SkipDependencyCheck behavior" -Text $install -Pattern 'if\s*\(\$SkipDependencyCheck\)\s*\{[\s\S]*Dependency checks skipped'
Assert-Contains -Name "install -SkipVMValidation behavior" -Text $install -Pattern 'if\s*\(\$SkipVMValidation\)\s*\{[\s\S]*VMware validation skipped'
Assert-Contains -Name "install skipped dependency summary" -Text $install -Pattern 'if\s*\(\$SkipDependencyCheck\)\s*\{[\s\S]*Dependency checks were skipped'
Assert-Contains -Name "install checks WSL xorriso" -Text $install -Pattern 'Test-WSLCommand[\s\S]*WSL xorriso'
Assert-Contains -Name "install checks VMware disk manager" -Text $install -Pattern 'Find-VmwareDiskManager[\s\S]*VMware disk manager'
Assert-Contains -Name "install checks ISO shape" -Text $install -Pattern 'Test-ISOReasonable[\s\S]*ISO warning'
Assert-Contains -Name "logger levels use script scope" -Text $logger -Pattern '\$script:LogLevels[\s\S]*\$levels\s*=\s*if\s*\(\$script:LogLevels\)'
Assert-Contains -Name "logs validates runtime" -Text $logs -Pattern 'Test-RuntimeExists\s+\$RuntimeName'
Assert-Contains -Name "sync start validates runtime" -Text $sync -Pattern '"start"[\s\S]*Test-RuntimeExists\s+\$RuntimeName'
Assert-Contains -Name "sync stop validates runtime" -Text $sync -Pattern '"stop"[\s\S]*Test-RuntimeExists\s+\$RuntimeName'
Assert-Contains -Name "sync validates subcommand before mutagen" -Text $sync -Pattern '\$validSubCommands[\s\S]*Unknown sync command[\s\S]*Initialize-Mutagen'
Assert-Contains -Name "doctor checks WSL xorriso" -Text $doctor -Pattern 'WSL xorriso'
Assert-Contains -Name "doctor checks ISO shape" -Text $doctor -Pattern 'ISO shape'
Assert-Contains -Name "doctor reports VMware NAT prerequisites" -Text $doctor -Pattern 'VMware NAT prerequisites[\s\S]*host VMnet8'
Assert-Contains -Name "doctor compares configured NAT to host VMnet8" -Text $doctor -Pattern 'Test-VMwareNatConfigMatchesHost[\s\S]*VMware NAT host match[\s\S]*VMware NAT gateway host range'
Assert-Contains -Name "doctor reports VMware running VM count accurately" -Text $doctor -Pattern 'Get-RunningVMs[\s\S]*VMware running VMs[\s\S]*running'
Assert-Contains -Name "up blocks VM creation on NAT mismatch" -Text $up -Pattern 'function\s+Assert-VMwareNatReadyForRuntimeCreate[\s\S]*VMware NAT mismatch detected before VM creation[\s\S]*No VM was created'
Assert-Contains -Name "status reports seed network drift" -Text (Read-Text "cli\commands\status.ps1") -Pattern 'network drift:[\s\S]*seed uses[\s\S]*Write-StatusNetworkDriftRemediation'
Assert-Contains -Name "status explains stale networking remediation paths" -Text (Read-Text "cli\commands\status.ps1") -Pattern 'function\s+Write-StatusNetworkDriftRemediation[\s\S]*Rebuild when the VM can be recreated[\s\S]*In-place guest fix[\s\S]*Admin-only temporary host-route workaround'
Assert-Contains -Name "status distinguishes SSH auth pending" -Text (Read-Text "cli\commands\status.ps1") -Pattern 'auth-pending[\s\S]*SSH port is open, but the ADP key is not accepted yet'
Assert-Contains -Name "status reports duplicate running runtime VMs" -Text (Read-Text "cli\commands\status.ps1") -Pattern 'ambiguous-duplicate[\s\S]*duplicate VM:[\s\S]*running ADP runtime name also found outside this checkout[\s\S]*other checkout or stale VM'
Assert-Contains -Name "doctor reports seed network drift" -Text $doctor -Pattern 'seed network drift[\s\S]*Write-NetworkDriftRemediation'
Assert-Contains -Name "doctor explains stale networking remediation paths" -Text $doctor -Pattern 'function\s+Write-NetworkDriftRemediation[\s\S]*Remediation options for \$TargetRuntime network drift[\s\S]*Rebuild when the VM can be recreated[\s\S]*In-place guest fix[\s\S]*Admin-only temporary host-route workaround'
Assert-Contains -Name "doctor reports duplicate running runtime VMs" -Text $doctor -Pattern 'duplicate running VM[\s\S]*Stop or rename stale duplicate ADP VMs before diagnosing SSH or network issues'
Assert-Contains -Name "network apply plan guides stale networking remediation" -Text $network -Pattern 'Network drift detected:[\s\S]*in-place guest netplan fix path only[\s\S]*adp destroy \$TargetRuntime -Plan[\s\S]*ADP will not add, change, or remove host routes automatically'
Assert-Contains -Name "network apply prefers seed-era SSH target during drift" -Text $network -Pattern 'if\s*\(-not\s+\$currentIp\s+-and\s+\$seedNetwork[\s\S]*\$currentIp\s*=\s*\$seedNetwork\.Address[\s\S]*if\s*\(-not\s+\$currentIp\)\s*\{[\s\S]*\$currentIp\s*=\s*\$network\.Address'
Assert-Contains -Name "VMware adapter detects host NAT network" -Text (Read-Text "adapters\windows\vmware\vmware.ps1") -Pattern 'function\s+Get-VMwareNatNetwork[\s\S]*function\s+Test-VMwareNatConfigMatchesHost'
Assert-Contains -Name "VMware adapter documents vmrun list as running-only" -Text (Read-Text "adapters\windows\vmware\vmware.ps1") -Pattern 'vmrun list returns only running VMs'
Assert-Contains -Name "VMware adapter classifies ADP running runtime VMs" -Text (Read-Text "adapters\windows\vmware\vmware.ps1") -Pattern 'function\s+Get-ADPRuntimeNameFromVmxPath[\s\S]*function\s+Get-ADPRunningRuntimeVMs[\s\S]*IsManagedByCurrentCheckout'
Assert-Contains -Name "VMware adapter exposes quick IP probe for progress loops" -Text (Read-Text "adapters\windows\vmware\vmware.ps1") -Pattern 'function\s+Get-VMIPQuick[\s\S]*getGuestIPAddress[\s\S]*Get-VMIPFromDhcpLeases'
Assert-Contains -Name "networking docs explain NAT prerequisites" -Text $networkingDocs -Pattern '## Prerequisites[\s\S]*Virtual Network Editor[\s\S]*VMware NAT prerequisites'
Assert-Contains -Name "Chinese networking docs explain NAT prerequisites" -Text $networkingDocsZh -Pattern '## 前置条件[\s\S]*Virtual Network Editor[\s\S]*VMware NAT prerequisites'
Assert-Contains -Name "operations docs explain duplicate runtime diagnostics" -Text (Read-Text "docs\operations.md") -Pattern 'duplicate running ADP runtime[\s\S]*same runtime name[\s\S]*another checkout or a stale VM store'
Assert-Contains -Name "Chinese operations docs explain duplicate runtime diagnostics" -Text (Read-Text "docs\zh-CN\operations.md") -Pattern 'duplicate running ADP runtime[\s\S]*另一个 checkout 或 stale VM store[\s\S]*同名 runtime'
Assert-Contains -Name "operations docs explain ambiguous duplicate SSH" -Text (Read-Text "docs\operations.md") -Pattern 'ambiguous-duplicate[\s\S]*does not prove that the current checkout'
Assert-Contains -Name "Chinese operations docs explain ambiguous duplicate SSH" -Text (Read-Text "docs\zh-CN\operations.md") -Pattern 'ambiguous-duplicate[\s\S]*不能证明响应的是当前 checkout'
Assert-Contains -Name "operations docs explain stale networking remediation paths" -Text (Read-Text "docs\operations.md") -Pattern 'network drift[\s\S]*Rebuild when the VM can be recreated[\s\S]*in-place guest netplan fix[\s\S]*administrator-only temporary host-route workaround[\s\S]*ADP does not add, change, or remove host routes automatically'
Assert-Contains -Name "Chinese operations docs explain stale networking remediation paths" -Text (Read-Text "docs\zh-CN\operations.md") -Pattern 'network drift[\s\S]*rebuild path[\s\S]*in-place guest netplan fix[\s\S]*administrator-only temporary host-route workaround[\s\S]*ADP 不会自动添加、修改或删除 host routes'
Assert-Contains -Name "troubleshooting docs mention duplicate runtime symptom" -Text $troubleshootingDocs -Pattern 'duplicate VM[\s\S]*same runtime name'
Assert-Contains -Name "Chinese troubleshooting docs mention duplicate runtime symptom" -Text $troubleshootingDocsZh -Pattern 'duplicate VM[\s\S]*同名 runtime'
Assert-Contains -Name "troubleshooting docs explain install monitor stuck symptom" -Text $troubleshootingDocs -Pattern 'Runtime creation looks stuck[\s\S]*\[install monitor\] INSTALLING Ubuntu[\s\S]*Ubuntu autoinstall'
Assert-Contains -Name "Chinese troubleshooting docs explain install monitor stuck symptom" -Text $troubleshootingDocsZh -Pattern 'Runtime 创建看起来卡住[\s\S]*\[install monitor\] INSTALLING Ubuntu[\s\S]*Ubuntu autoinstall'
Assert-Contains -Name "troubleshooting docs explain stale networking remediation paths" -Text $troubleshootingDocs -Pattern 'network drift[\s\S]*network apply <runtime> -Plan[\s\S]*Rebuild the runtime[\s\S]*administrator-only temporary host-route workaround'
Assert-Contains -Name "Chinese troubleshooting docs explain stale networking remediation paths" -Text $troubleshootingDocsZh -Pattern 'network drift[\s\S]*network apply <runtime> -Plan[\s\S]*重建该 runtime[\s\S]*administrator-only temporary host-route workaround'
Assert-Contains -Name "workspace docs mention recipes example" -Text $workspaceDocs -Pattern 'configs/workspace\.recipes\.example\.json'
Assert-Contains -Name "Chinese workspace docs mention recipes example" -Text $workspaceDocsZh -Pattern 'configs/workspace\.recipes\.example\.json'
Assert-Contains -Name "workspace docs define recipes discovery view" -Text $workspaceDocs -Pattern 'workspace recipes -ManifestPath configs\\workspace\.recipes\.example\.json[\s\S]*manifest discovery view[\s\S]*without cloning projects, opening SSH, starting sync, creating snapshots, running validation, running evaluation commands, running Git, or modifying files'
Assert-Contains -Name "Chinese workspace docs define recipes discovery view" -Text $workspaceDocsZh -Pattern 'workspace recipes -ManifestPath configs\\workspace\.recipes\.example\.json[\s\S]*manifest discovery view[\s\S]*不会 clone project、打开 SSH、启动 sync、创建快照、运行 validation、运行 evaluation commands、运行 Git 或修改文件'
Assert-Contains -Name "workspace docs define create boundary" -Text $workspaceDocs -Pattern 'workspace create -Plan[\s\S]*workspace create[\s\S]*creates only missing local project directories[\s\S]*does not clone repositories, start runtimes, start or stop sync, open SSH, create snapshots, run validation, run evaluation commands, run Git, or modify existing project files'
Assert-Contains -Name "Chinese workspace docs define create boundary" -Text $workspaceDocsZh -Pattern 'workspace create -Plan[\s\S]*workspace create[\s\S]*只会创建从 `projects\[\]\.path` 解析出的缺失本地项目目录[\s\S]*不会 clone repository、启动 runtime、启动或停止 sync、打开 SSH、创建快照、运行 validation、运行 evaluation commands、运行 Git'
Assert-Contains -Name "workspace docs define open guide" -Text $workspaceDocs -Pattern 'workspace open app[\s\S]*workspace open frontend-app[\s\S]*non-destructive open guide[\s\S]*does not create directories, open an editor, start a shell, connect over SSH, start sync, start a runtime, or modify files'
Assert-Contains -Name "Chinese workspace docs define open guide" -Text $workspaceDocsZh -Pattern 'workspace open app[\s\S]*workspace open frontend-app[\s\S]*非破坏性的 open guide[\s\S]*不会创建目录、打开编辑器、启动 shell、通过 SSH 连接、启动 sync、启动 runtime 或修改文件'
Assert-Contains -Name "workspace docs define project sync guide" -Text $workspaceDocs -Pattern 'workspace sync app[\s\S]*workspace sync frontend-app[\s\S]*non-destructive project-aware sync guide[\s\S]*does not start or stop Mutagen, create directories, start runtimes, connect over SSH, or modify files'
Assert-Contains -Name "Chinese workspace docs define project sync guide" -Text $workspaceDocsZh -Pattern 'workspace sync app[\s\S]*workspace sync frontend-app[\s\S]*非破坏性的 project-aware sync guide[\s\S]*不会启动或停止 Mutagen、创建目录、启动 runtime、通过 SSH 连接或修改文件'
Assert-Contains -Name "workspace docs define project lifecycle view" -Text $workspaceDocs -Pattern 'workspace project app[\s\S]*workspace project frontend-app[\s\S]*non-destructive lifecycle view[\s\S]*does not open the project, start a runtime, start or stop sync, create snapshots, run validation, run Git, connect over SSH, or modify files'
Assert-Contains -Name "Chinese workspace docs define project lifecycle view" -Text $workspaceDocsZh -Pattern 'workspace project app[\s\S]*workspace project frontend-app[\s\S]*非破坏性 lifecycle view[\s\S]*不会打开项目、启动 runtime、启动或停止 sync、创建快照、运行验证、运行 Git、通过 SSH 连接或修改文件'
Assert-Contains -Name "workspace docs define snapshot naming convention" -Text $workspaceDocs -Pattern 'Snapshot names should be tied to task or milestone intent[\s\S]*before-<task-name>[\s\S]*milestone-<name>[\s\S]*non-blocking convention check'
Assert-Contains -Name "Chinese workspace docs define snapshot naming convention" -Text $workspaceDocsZh -Pattern 'Snapshot 名称应该绑定 task 或 milestone 意图[\s\S]*before-<task-name>[\s\S]*milestone-<name>[\s\S]*非阻塞约定检查'
Assert-Contains -Name "workspace docs define milestone planning" -Text $workspaceDocs -Pattern 'Milestones are optional manifest-level planning records[\s\S]*milestones\[\]\.tasks[\s\S]*tasks\[\]\.milestone'
Assert-Contains -Name "workspace docs define milestone default snapshot gate" -Text $workspaceDocs -Pattern 'tasks\[\]\.milestone[\s\S]*defaults to snapshot-first gating'
Assert-Contains -Name "Chinese workspace docs define milestone planning" -Text $workspaceDocsZh -Pattern 'Milestone 是可选的 manifest-level planning record[\s\S]*milestones\[\]\.tasks[\s\S]*tasks\[\]\.milestone'
Assert-Contains -Name "Chinese workspace docs define milestone default snapshot gate" -Text $workspaceDocsZh -Pattern 'tasks\[\]\.milestone[\s\S]*默认触发 snapshot-first gate'
Assert-Contains -Name "workspace docs define evaluation hooks" -Text $workspaceDocs -Pattern 'Evaluations are optional manifest-level planning records[\s\S]*evaluations\[\][\s\S]*Evaluation Queue[\s\S]*evaluations\[\]\.metrics[\s\S]*tasks\[\]\.evaluation'
Assert-Contains -Name "Chinese workspace docs define evaluation hooks" -Text $workspaceDocsZh -Pattern 'Evaluation 是可选的 manifest-level planning record[\s\S]*evaluations\[\][\s\S]*Evaluation Queue[\s\S]*evaluations\[\]\.metrics[\s\S]*tasks\[\]\.evaluation'
Assert-Contains -Name "docs index links release readiness" -Text (Read-Text "docs\README.md") -Pattern 'Release Readiness\]\(release-readiness\.md\)'
Assert-Contains -Name "Chinese docs index links release readiness" -Text (Read-Text "docs\zh-CN\README.md") -Pattern '发布就绪\]\(release-readiness\.md\)'
Assert-Contains -Name "docs index links release process" -Text (Read-Text "docs\README.md") -Pattern 'Release Process\]\(release-process\.md\)'
Assert-Contains -Name "Chinese docs index links release process" -Text (Read-Text "docs\zh-CN\README.md") -Pattern '发布流程\]\(release-process\.md\)'
Assert-Contains -Name "docs index links contributor workflows" -Text (Read-Text "docs\README.md") -Pattern 'Contributor Workflows\]\(contributor-workflows\.md\)'
Assert-Contains -Name "Chinese docs index links contributor workflows" -Text (Read-Text "docs\zh-CN\README.md") -Pattern '贡献者工作流\]\(contributor-workflows\.md\)'
Assert-Contains -Name "README links release readiness" -Text (Read-Text "README.md") -Pattern 'Release Readiness\]\(docs/release-readiness\.md\)'
Assert-Contains -Name "Chinese README links release readiness" -Text (Read-Text "README.zh-CN.md") -Pattern '发布就绪\]\(docs/zh-CN/release-readiness\.md\)'
Assert-Contains -Name "README links release process" -Text (Read-Text "README.md") -Pattern 'Release Process\]\(docs/release-process\.md\)'
Assert-Contains -Name "Chinese README links release process" -Text (Read-Text "README.zh-CN.md") -Pattern '发布流程\]\(docs/zh-CN/release-process\.md\)'
Assert-Contains -Name "README links contributor workflows" -Text (Read-Text "README.md") -Pattern 'Contributor Workflows\]\(docs/contributor-workflows\.md\)'
Assert-Contains -Name "Chinese README links contributor workflows" -Text (Read-Text "README.zh-CN.md") -Pattern '贡献者工作流\]\(docs/zh-CN/contributor-workflows\.md\)'
Assert-Contains -Name "release readiness docs define decision policy" -Text $releaseReadinessDocs -Pattern '## Release Decision Policy[\s\S]*release candidate[\s\S]*sync hygiene is not blocking[\s\S]*release blocked[\s\S]*sync hygiene, a snapshot gate, or failed validation[\s\S]*validation required[\s\S]*review required[\s\S]*governance incomplete'
Assert-Contains -Name "release readiness docs define maintainer checklist" -Text $releaseReadinessDocs -Pattern '## Maintainer Checklist[\s\S]*adp workspace dashboard[\s\S]*adp workspace report[\s\S]*review sync ignore[\s\S]*release candidate[\s\S]*sync hygiene reviewed'
Assert-Contains -Name "release readiness docs include snapshot naming convention" -Text $releaseReadinessDocs -Pattern 'Snapshot naming is reviewed as part of rollback clarity[\s\S]*before-<task-name>[\s\S]*milestone-<name>[\s\S]*Naming convention warnings are non-blocking'
Assert-Contains -Name "Chinese release readiness docs define decision policy" -Text $releaseReadinessDocsZh -Pattern '## 发布决策策略[\s\S]*release candidate[\s\S]*sync hygiene 未阻塞[\s\S]*release blocked[\s\S]*sync hygiene、snapshot gate 或失败 validation[\s\S]*validation required[\s\S]*review required[\s\S]*governance incomplete'
Assert-Contains -Name "Chinese release readiness docs define maintainer checklist" -Text $releaseReadinessDocsZh -Pattern '## 维护者检查清单[\s\S]*adp workspace dashboard[\s\S]*adp workspace report[\s\S]*review sync ignore[\s\S]*release candidate[\s\S]*sync hygiene 已 review'
Assert-Contains -Name "Chinese release readiness docs include snapshot naming convention" -Text $releaseReadinessDocsZh -Pattern 'Snapshot naming 也是 rollback clarity 的 review 内容[\s\S]*before-<task-name>[\s\S]*milestone-<name>[\s\S]*不阻塞 release'
Assert-Contains -Name "release process docs define maintainer flow" -Text $releaseProcessDocs -Pattern '## Maintainer Flow[\s\S]*\.\\tests\\validate\.ps1 -Quick[\s\S]*\.\\tests\\validate\.ps1[\s\S]*workspace report -Markdown[\s\S]*owner has authorized publication'
Assert-Contains -Name "release process docs include sync hygiene evidence" -Text $releaseProcessDocs -Pattern '## Evidence Expectations[\s\S]*Sync hygiene status[\s\S]*review sync ignore[\s\S]*reviewed before release'
Assert-Contains -Name "release process docs define safety checks" -Text $releaseProcessDocs -Pattern '## Safety Checks[\s\S]*Secrets[\s\S]*adp-workspace\.state\.json[\s\S]*private maintainer'
Assert-Contains -Name "Chinese release process docs define maintainer flow" -Text $releaseProcessDocsZh -Pattern '## 维护者流程[\s\S]*\.\\tests\\validate\.ps1 -Quick[\s\S]*\.\\tests\\validate\.ps1[\s\S]*workspace report -Markdown[\s\S]*repository owner 授权发布'
Assert-Contains -Name "Chinese release process docs include sync hygiene evidence" -Text $releaseProcessDocsZh -Pattern 'Evidence 应显示：[\s\S]*Sync hygiene status[\s\S]*发布前必须 review[\s\S]*review sync ignore'
Assert-Contains -Name "Chinese release process docs define safety checks" -Text $releaseProcessDocsZh -Pattern '## 安全检查[\s\S]*Secrets[\s\S]*adp-workspace\.state\.json[\s\S]*Private maintainer'
Assert-Contains -Name "contributor workflow docs include templates" -Text $contributorWorkflowDocs -Pattern '## Workflow Templates[\s\S]*Documentation or Small Maintenance[\s\S]*Frontend Browser Acceptance[\s\S]*Backend Validation[\s\S]*Broad Agent Refactor'
Assert-Contains -Name "contributor workflow docs include maintainer ritual" -Text $contributorWorkflowDocs -Pattern '## Maintainer Review Ritual[\s\S]*adp workspace dashboard[\s\S]*adp workspace report[\s\S]*review sync ignore[\s\S]*release candidate'
Assert-Contains -Name "contributor workflow docs include sync hygiene PR expectation" -Text $contributorWorkflowDocs -Pattern '## Pull Request Expectations[\s\S]*Sync hygiene status[\s\S]*review sync ignore'
Assert-Contains -Name "contributor workflow docs include snapshot naming expectation" -Text $contributorWorkflowDocs -Pattern 'before-<task-name>[\s\S]*milestone-<name>[\s\S]*snapshot name communicates task or milestone rollback intent'
Assert-Contains -Name "Chinese contributor workflow docs include templates" -Text $contributorWorkflowDocsZh -Pattern '## 工作流模板[\s\S]*文档或小型维护[\s\S]*前端浏览器验收[\s\S]*后端验证[\s\S]*大范围 Agent 重构'
Assert-Contains -Name "Chinese contributor workflow docs include maintainer ritual" -Text $contributorWorkflowDocsZh -Pattern '## 维护者评审流程[\s\S]*adp workspace dashboard[\s\S]*adp workspace report[\s\S]*review sync ignore[\s\S]*release candidate'
Assert-Contains -Name "Chinese contributor workflow docs include sync hygiene PR expectation" -Text $contributorWorkflowDocsZh -Pattern '## Pull Request 预期[\s\S]*Sync hygiene status[\s\S]*review sync ignore'
Assert-Contains -Name "Chinese contributor workflow docs include snapshot naming expectation" -Text $contributorWorkflowDocsZh -Pattern 'before-<task-name>[\s\S]*milestone-<name>[\s\S]*snapshot 名称是否表达 task 或 milestone rollback 意图'
Assert-Contains -Name "PR template asks for shared validation" -Text $pullRequestTemplate -Pattern '## Validation[\s\S]*\.\\tests\\validate\.ps1[\s\S]*\.\\tests\\validate\.ps1 -Quick'
Assert-Contains -Name "PR template asks for release readiness" -Text $pullRequestTemplate -Pattern '## Release Readiness[\s\S]*workspace task shape[\s\S]*workspace report -Markdown[\s\S]*Stale-task remediation[\s\S]*Sync hygiene[\s\S]*review sync ignore[\s\S]*snapshot gate'
Assert-Contains -Name "doctor supports Mutagen remediation plan" -Text $doctor -Pattern '\[switch\]\$FixMutagen[\s\S]*\[switch\]\$Plan[\s\S]*Install-LocalMutagen[\s\S]*Plan only: no files will be downloaded'
Assert-Contains -Name "doctor rejects plan without Mutagen remediation" -Text $doctor -Pattern '-Plan is only supported with -FixMutagen'
Assert-Contains -Name "mutagen adapter installs local ignored binary" -Text (Read-Text "adapters\windows\mutagen\mutagen.ps1") -Pattern 'function\s+Install-LocalMutagen[\s\S]*mutagen_windows_amd64_v\$Version\.zip[\s\S]*Expand-Archive[\s\S]*Test-MutagenVersionSupported'
Assert-Contains -Name "workspace init uses public example manifest" -Text $workspace -Pattern 'configs\\workspace\.example\.json'
Assert-Contains -Name "workspace plan is non-destructive" -Text $workspace -Pattern 'Plan only: no projects will be cloned, no sync sessions will be changed, and no snapshots will be created'
Assert-Contains -Name "workspace plan suggests previewed runtime startup" -Text $workspace -Pattern 'adp up \$\(\$project\.runtime\) -Plan'
Assert-Contains -Name "workspace plan suggests milestone checkpoints" -Text $workspace -Pattern 'Get-WorkspaceMilestones[\s\S]*Milestone checkpoint.*adp snapshot create \$\(\$milestoneStatus\.RuntimeName\) \$\(\$milestoneStatus\.SnapshotName\)'
Assert-Contains -Name "workspace recipes is non-destructive" -Text $workspace -Pattern 'function\s+Write-WorkspaceRecipes[\s\S]*Recipes only: no projects will be cloned, no sync sessions will be changed, no snapshots will be created, no validation or evaluation commands will be run, no SSH connection will be opened, and no Git commands will be run'
Assert-Contains -Name "workspace recipes summarizes projects tasks evaluations and evidence" -Text $workspace -Pattern 'function\s+Write-WorkspaceRecipes[\s\S]*Project recipes:[\s\S]*Task recipes:[\s\S]*Milestone recipes:[\s\S]*Evaluation recipes:[\s\S]*Evidence commands:'
Assert-Contains -Name "workspace recipes command route" -Text $workspace -Pattern '"recipes"\s*\{[\s\S]*Write-WorkspaceRecipes\s+-Manifest\s+\$manifest\s+-ManifestPath\s+\$ManifestPath\s+-StatePath\s+\$StatePath'
Assert-Contains -Name "workspace create supports plan and guarded creation" -Text $workspace -Pattern 'function\s+Write-WorkspaceCreate[\s\S]*Plan only: no directories will be created[\s\S]*no validation or evaluation commands run[\s\S]*Create only: local project directories may be created[\s\S]*no validation or evaluation commands run[\s\S]*New-Item -ItemType Directory[\s\S]*No projects will be cloned'
Assert-Contains -Name "workspace create blocks invalid paths before creation" -Text $workspace -Pattern 'function\s+Get-WorkspaceProjectCreateEntries[\s\S]*refusing to create a filesystem root[\s\S]*path exists and is not a directory[\s\S]*Create blocked: fix invalid project paths before creating workspace directories'
Assert-Contains -Name "workspace create command route" -Text $workspace -Pattern '"create"\s*\{[\s\S]*Write-WorkspaceCreate\s+-Manifest\s+\$manifest\s+-ManifestPath\s+\$ManifestPath\s+-PlanOnly:\$Plan'
Assert-Contains -Name "workspace open is non-destructive" -Text $workspace -Pattern 'function\s+Write-WorkspaceOpen[\s\S]*Open guide only: no shell, editor, SSH connection, sync session, runtime, or file will be changed[\s\S]*Local commands:[\s\S]*Runtime commands:[\s\S]*Next:'
Assert-Contains -Name "workspace open resolves project names" -Text $workspace -Pattern 'function\s+Find-WorkspaceProject[\s\S]*Project name required because the workspace has multiple projects[\s\S]*Workspace project not found'
Assert-Contains -Name "workspace open command route" -Text $workspace -Pattern '"open"\s*\{[\s\S]*Write-WorkspaceOpen\s+-Manifest\s+\$manifest\s+-ProjectName\s+\$TaskCommand\s+-ManifestPath\s+\$ManifestPath'
Assert-Contains -Name "workspace sync is non-destructive" -Text $workspace -Pattern 'function\s+Write-WorkspaceSyncGuide[\s\S]*Sync guide only: no Mutagen session, runtime, SSH connection, directory, or file will be changed[\s\S]*Runtime sync commands:[\s\S]*adp sync start \$runtimeName[\s\S]*adp sync stop \$runtimeName'
Assert-Contains -Name "workspace sync command route" -Text $workspace -Pattern '"sync"\s*\{[\s\S]*Write-WorkspaceSyncGuide\s+-Manifest\s+\$manifest\s+-ProjectName\s+\$TaskCommand\s+-ManifestPath\s+\$ManifestPath'
Assert-Contains -Name "workspace project is non-destructive" -Text $workspace -Pattern 'function\s+Write-WorkspaceProjectLifecycle[\s\S]*Lifecycle view only: no project, runtime, sync session, snapshot, validation command, Git command, or file will be changed[\s\S]*Lifecycle gates:[\s\S]*Operational flow:[\s\S]*Linked tasks:'
Assert-Contains -Name "workspace project links tasks" -Text $workspace -Pattern 'function\s+Get-WorkspaceTasksForProject[\s\S]*\$taskProject[\s\S]*\$matched\.Add\(\$task\)[\s\S]*function\s+Write-WorkspaceProjectLifecycle[\s\S]*Get-WorkspaceTasksForProject[\s\S]*Get-WorkspaceCommitDecision'
Assert-Contains -Name "workspace project command route" -Text $workspace -Pattern '"project"\s*\{[\s\S]*Write-WorkspaceProjectLifecycle\s+-Manifest\s+\$manifest\s+-ProjectName\s+\$TaskCommand\s+-ManifestPath\s+\$ManifestPath\s+-StatePath\s+\$StatePath'
Assert-Contains -Name "workspace status is non-destructive" -Text $workspace -Pattern 'Status only: no projects will be cloned, no sync sessions will be changed, no snapshots will be created, and no validation or evaluation commands will be run'
Assert-Contains -Name "workspace status checks runtime readiness" -Text $workspace -Pattern 'Get-WorkspaceRuntimeStatus'
Assert-Contains -Name "workspace status checks sync readiness" -Text $workspace -Pattern 'Get-WorkspaceSyncStatus'
Assert-Contains -Name "workspace status checks sync hygiene non-destructively" -Text $workspace -Pattern 'function\s+Get-WorkspaceSyncHygieneStatus[\s\S]*node_modules[\s\S]*not ignored by sync profile[\s\S]*generated directories ignored by sync profile'
Assert-Contains -Name "workspace sync hygiene checks expanded generated directories" -Text $workspace -Pattern 'function\s+Get-WorkspaceSyncHygieneStatus[\s\S]*\.parcel-cache[\s\S]*\.vite[\s\S]*\.playwright[\s\S]*\.mypy_cache[\s\S]*\.ruff_cache'
Assert-Contains -Name "config schema requires expanded default sync profile ignores" -Text (Read-Text "tests\config-schema.ps1") -Pattern 'requiredIgnores[\s\S]*frontend = @\("node_modules", "\.next", "dist", "build", "coverage"[\s\S]*backend\s+= @\("dist", "build", "coverage", "__pycache__", "\.venv"[\s\S]*agent\s+= @\("node_modules", "\.git", "\.venv"[\s\S]*"\.codex", "\.claude", "\.tools", "logs"'
Assert-Contains -Name "configuration docs explain sync profile array replacement" -Text (Read-Text "docs\configuration.md") -Pattern 'Arrays and scalar values replace the default value, so local `sync_profiles\.<name>\.ignore` overrides should include every ignored path'
Assert-Contains -Name "Chinese configuration docs explain sync profile array replacement" -Text (Read-Text "docs\zh-CN\configuration.md") -Pattern '数组和标量值会替换默认值，因此本地 `sync_profiles\.<name>\.ignore` 覆盖应包含你仍然想保留的所有默认忽略路径'
Assert-Contains -Name "workspace status checks snapshot readiness" -Text $workspace -Pattern 'Get-WorkspaceSnapshotStatus'
Assert-Contains -Name "workspace status checks snapshot naming non-destructively" -Text $workspace -Pattern 'function\s+Get-WorkspaceRecommendedSnapshotName[\s\S]*return "before-\$taskName"[\s\S]*function\s+Get-WorkspaceSnapshotNamingStatus[\s\S]*Status\s+=\s+"nonstandard"[\s\S]*milestone-<name>'
Assert-Contains -Name "workspace supports milestone checkpoint helpers" -Text $workspace -Pattern 'function\s+Get-WorkspaceMilestones[\s\S]*function\s+Get-WorkspaceRecommendedMilestoneSnapshotName[\s\S]*return "milestone-\$name"[\s\S]*function\s+Get-WorkspaceTaskMilestones[\s\S]*function\s+Get-WorkspaceMilestoneStatus'
Assert-Contains -Name "workspace supports evaluation hook helpers" -Text $workspace -Pattern 'function\s+Get-WorkspaceEvaluations[\s\S]*function\s+Get-WorkspaceEvaluationTasks[\s\S]*function\s+Get-WorkspaceTaskEvaluations[\s\S]*function\s+Get-WorkspaceEvaluationStatus'
Assert-Contains -Name "workspace milestone tasks default to snapshot gate unless overridden" -Text $workspace -Pattern 'function\s+Test-WorkspaceTaskRequiresSnapshot[\s\S]*requires_snapshot[\s\S]*-contains "milestone"[\s\S]*return \$true[\s\S]*Get-WorkspaceTaskRisk'
Assert-Contains -Name "workspace detects devcontainer metadata non-destructively" -Text $workspace -Pattern 'function\s+Get-WorkspaceDevContainerStatus[\s\S]*\.devcontainer/devcontainer\.json[\s\S]*Docker/dev container metadata can still be used inside the ADP runtime'
Assert-Contains -Name "workspace task risk supports snapshot gating" -Text $workspace -Pattern 'function\s+Get-WorkspaceTaskRisk[\s\S]*function\s+Test-WorkspaceTaskRequiresSnapshot[\s\S]*function\s+Get-WorkspaceSnapshotGate'
Assert-Contains -Name "workspace checkpoint waiver is local state only" -Text $workspace -Pattern 'function\s+Set-WorkspaceTaskCheckpointWaiver[\s\S]*state\s+=\s+"checkpoint-waived"[\s\S]*checkpoint\s*=\s*\$checkpoint[\s\S]*function\s+Test-WorkspaceCheckpointWaived[\s\S]*checkpoint-waived'
Assert-Contains -Name "workspace snapshot gate treats real snapshot before waiver" -Text $workspace -Pattern 'function\s+Get-WorkspaceSnapshotGate[\s\S]*if\s*\(\$SnapshotStatus\.Level\s+-eq\s+"OK"\)[\s\S]*Status\s+=\s+"ready"[\s\S]*if\s*\(Test-WorkspaceCheckpointWaived'
Assert-Contains -Name "workspace checkpointed clears waiver marker" -Text $workspace -Pattern 'function\s+Set-WorkspaceTaskState[\s\S]*if\s*\(\$StateName\s+-eq\s+"checkpointed"[\s\S]*PSObject\.Properties\.Remove\("checkpoint"\)'
Assert-Contains -Name "workspace dashboard is non-destructive" -Text $workspace -Pattern 'Dashboard only: no projects will be cloned, no sync sessions will be changed, no snapshots will be created, no validation or evaluation commands will be run, and no Git commands will be run'
Assert-Contains -Name "workspace dashboard includes sync hygiene rollup" -Text $workspace -Pattern 'sync hygiene: \$\(\$syncHygieneStatus\.Status\)'
Assert-Contains -Name "workspace dashboard includes snapshot naming rollup" -Text $workspace -Pattern 'snapshot naming: \$\(\$snapshotNaming\.Status\)'
Assert-Contains -Name "workspace dashboard includes milestone checkpoints" -Text $workspace -Pattern 'Milestone checkpoints:[\s\S]*Get-WorkspaceMilestoneStatus[\s\S]*milestone: \$milestoneText'
Assert-Contains -Name "workspace dashboard includes evaluation hooks" -Text $workspace -Pattern 'Evaluation hooks:[\s\S]*Get-WorkspaceEvaluationStatus[\s\S]*evaluation: \$evaluationText'
Assert-Contains -Name "workspace dashboard summarizes lifecycle state" -Text $workspace -Pattern 'Task lifecycle:[\s\S]*snapshot required:[\s\S]*execution:[\s\S]*rollback:[\s\S]*commit:'
Assert-Contains -Name "workspace dashboard can block execution on snapshot gate" -Text $workspace -Pattern 'blocked by snapshot gate'
Assert-Contains -Name "workspace dashboard reads checkpoint waiver state" -Text $workspace -Pattern 'function\s+Write-WorkspaceDashboard[\s\S]*Get-WorkspaceTaskState[\s\S]*Get-WorkspaceSnapshotGate\s+-Task\s+\$task\s+-SnapshotStatus\s+\$snapshotStatus\s+-RecordedState\s+\$recordedState'
Assert-Contains -Name "workspace dashboard uses shared commit readiness gate" -Text $workspace -Pattern 'function\s+Write-WorkspaceDashboard[\s\S]*Get-WorkspaceTaskSyncHygieneStatus[\s\S]*Get-WorkspaceCommitDecision[\s\S]*commit: \$commitState'
Assert-Contains -Name "workspace report is non-destructive" -Text $workspace -Pattern 'Report only: no projects will be cloned, no sync sessions will be changed, no snapshots will be created, no validation or evaluation commands will be run, and no Git commands will be run'
Assert-Contains -Name "workspace report supports Markdown evidence" -Text $workspace -Pattern '\[switch\]\$Markdown[\s\S]*function\s+Write-WorkspaceReportMarkdown[\s\S]*Workspace Release Evidence[\s\S]*Markdown report only[\s\S]*Task Evidence[\s\S]*Maintainer Checklist'
Assert-Contains -Name "workspace report normalizes Markdown evidence paths" -Text $workspace -Pattern 'function\s+Format-WorkspaceEvidencePath[\s\S]*Get-ProjectRoot[\s\S]*Local state \| \$\(Format-WorkspaceMarkdownValue \(Format-WorkspaceEvidencePath \$resolvedStatePath\)\)'
Assert-Contains -Name "workspace report routes Markdown evidence" -Text $workspace -Pattern '"report"\s*\{[\s\S]*Write-WorkspaceReport\s+-Manifest\s+\$manifest\s+-ManifestPath\s+\$ManifestPath\s+-StatePath\s+\$StatePath\s+-Markdown:\$Markdown'
Assert-Contains -Name "workspace report summarizes task decisions" -Text $workspace -Pattern 'function\s+Write-WorkspaceReport[\s\S]*validation result:[\s\S]*review:[\s\S]*rollback:[\s\S]*commit:'
Assert-Contains -Name "workspace report includes sync hygiene release evidence" -Text $workspace -Pattern 'function\s+New-WorkspaceReportItem[\s\S]*Get-WorkspaceTaskSyncHygieneStatus[\s\S]*review sync ignore[\s\S]*release blocked[\s\S]*function\s+Write-WorkspaceReportMarkdown[\s\S]*Sync hygiene[\s\S]*function\s+Write-WorkspaceReport[\s\S]*sync hygiene:'
Assert-Contains -Name "workspace report includes snapshot naming evidence" -Text $workspace -Pattern 'function\s+New-WorkspaceReportItem[\s\S]*Get-WorkspaceSnapshotNamingStatus[\s\S]*SnapshotNaming[\s\S]*Write-WorkspaceReportMarkdown[\s\S]*naming: \$\(\$item\.SnapshotNaming\.Status\)[\s\S]*Write-WorkspaceReport[\s\S]*snapshot naming: \$\(\$item\.SnapshotNaming\.Status\)'
Assert-Contains -Name "workspace report reads checkpoint waiver state" -Text $workspace -Pattern 'function\s+New-WorkspaceReportItem[\s\S]*Get-WorkspaceTaskState[\s\S]*Get-WorkspaceSnapshotGate\s+-Task\s+\$Task\s+-SnapshotStatus\s+\$snapshotStatus\s+-RecordedState\s+\$recordedState'
Assert-Contains -Name "workspace report includes milestone release evidence" -Text $workspace -Pattern 'function\s+New-WorkspaceReportItem[\s\S]*Get-WorkspaceTaskMilestones[\s\S]*MilestoneText[\s\S]*function\s+Write-WorkspaceMilestoneCheckpoints[\s\S]*Milestone checkpoints:[\s\S]*function\s+Get-WorkspaceMilestoneReviewRollups[\s\S]*function\s+Write-WorkspaceMilestoneReviewRollup[\s\S]*Milestone review rollup:[\s\S]*function\s+Write-WorkspaceReportMarkdown[\s\S]*## Milestone Checkpoints[\s\S]*## Milestone Review Rollup[\s\S]*\| Task \| Milestone \| Evaluation \| Owner \| Runtime'
Assert-Contains -Name "workspace report includes evaluation queue evidence" -Text $workspace -Pattern 'function\s+Get-WorkspaceEvaluationQueueItems[\s\S]*function\s+Write-WorkspaceEvaluationQueue[\s\S]*Evaluation queue:[\s\S]*Evaluation queue only: no evaluation commands will be run[\s\S]*function\s+Write-WorkspaceReportMarkdown[\s\S]*## Evaluation Queue[\s\S]*No evaluation commands were run[\s\S]*\| Task \| Milestone \| Evaluation \| Owner \| Runtime'
Assert-Contains -Name "workspace report checklist includes sync hygiene gate" -Text $workspace -Pattern 'Maintainer Checklist[\s\S]*Confirm sync hygiene is clean, covered, not requested, or intentionally reviewed before release[\s\S]*commit only after sync hygiene, validation, and human review are all accepted'
Assert-Contains -Name "workspace report has release handoff summary" -Text $workspace -Pattern 'function\s+Write-WorkspaceReportSummary[\s\S]*Release handoff summary:[\s\S]*blocked tasks:[\s\S]*ready for review:[\s\S]*ready to commit:[\s\S]*release gate:'
Assert-Contains -Name "workspace report has governance fields" -Text $workspace -Pattern 'function\s+New-WorkspaceReportItem[\s\S]*OwnerName[\s\S]*ReviewCadence[\s\S]*DueStatus[\s\S]*function\s+Write-WorkspaceReportSummary[\s\S]*owner gaps:[\s\S]*cadence gaps:[\s\S]*due attention:'
Assert-Contains -Name "workspace report has governance loop" -Text $workspace -Pattern 'function\s+Write-WorkspaceGovernanceLoop[\s\S]*Governance loop:[\s\S]*owner queues:[\s\S]*review cadence:[\s\S]*attention queue:'
Assert-Contains -Name "workspace report has decision queues" -Text $workspace -Pattern 'function\s+Write-WorkspaceDecisionQueues[\s\S]*Decision queues:[\s\S]*actions:[\s\S]*release readiness:[\s\S]*action:[\s\S]*release readiness:'
Assert-Contains -Name "workspace report has validation execution queue" -Text $workspace -Pattern 'function\s+Get-WorkspaceValidationQueueItems[\s\S]*ready to execute[\s\S]*ExecutePreview[\s\S]*function\s+Write-WorkspaceValidationQueue[\s\S]*Validation execution queue:[\s\S]*execute preview:[\s\S]*function\s+Write-WorkspaceReportMarkdown[\s\S]*## Validation Execution Queue'
Assert-Contains -Name "workspace report has release policy" -Text $workspace -Pattern 'function\s+Write-WorkspaceReleasePolicy[\s\S]*Release decision policy:[\s\S]*decision:[\s\S]*blockers:[\s\S]*validation required:[\s\S]*review required:[\s\S]*release candidates:'
Assert-Contains -Name "workspace report has stale remediation" -Text $workspace -Pattern 'function\s+Write-WorkspaceStaleTaskRemediation[\s\S]*Stale-task remediation:[\s\S]*owner=.*cadence=.*timing=.*action=.*release='
Assert-Contains -Name "workspace run prints snapshot-first gate" -Text $workspace -Pattern 'Snapshot-first gate before broad agent work'
Assert-Contains -Name "workspace task snapshot prints snapshot naming convention" -Text $workspace -Pattern 'function\s+Write-WorkspaceTaskSnapshot[\s\S]*snapshot naming[\s\S]*Explicit command to create the checkpoint'
Assert-Contains -Name "workspace task snapshot prints waiver command" -Text $workspace -Pattern 'function\s+Write-WorkspaceTaskSnapshot[\s\S]*If the human reviewer intentionally accepts missing snapshot protection[\s\S]*adp workspace task mark \$\(\$Task\.name\) checkpoint-waived'
Assert-Contains -Name "workspace validate supports explicit execution" -Text $workspace -Pattern '\[switch\]\$Execute[\s\S]*\[switch\]\$Plan[\s\S]*function\s+Invoke-WorkspaceRemoteValidationCommand[\s\S]*Write-WorkspaceTaskValidate'
Assert-Contains -Name "workspace validate execution is scoped to validate command" -Text $workspace -Pattern '-Execute and -Plan are only supported with: adp workspace task validate <task-name>'
Assert-Contains -Name "workspace validate execution resolves task project" -Text $workspace -Pattern 'Find-WorkspaceProjectForTask[\s\S]*tasks\[\]\.project'
Assert-Contains -Name "workspace validate execution rejects unsafe project paths" -Text $workspace -Pattern 'Resolve-WorkspaceRemoteProjectPath[\s\S]*path cannot contain'
Assert-Contains -Name "workspace validate execution records validation result" -Text $workspace -Pattern 'Set-WorkspaceTaskValidationResult[\s\S]*validation_failed[\s\S]*Write-WorkspaceValidationResult'
Assert-Contains -Name "workspace validate execution prints readiness gate" -Text $workspace -Pattern 'Readiness gate:[\s\S]*snapshot-first gate[\s\S]*ssh target'
Assert-Contains -Name "workspace dashboard displays validation result" -Text $workspace -Pattern 'Format-WorkspaceValidationState[\s\S]*validation result:'
Assert-Contains -Name "workspace review displays validation result" -Text $workspace -Pattern 'recorded validation:[\s\S]*Write-WorkspaceValidationDetailLines[\s\S]*state file:'
Assert-Contains -Name "workspace review has decision gate" -Text $workspace -Pattern 'function\s+Get-WorkspaceReviewDecision[\s\S]*blocked by sync hygiene[\s\S]*validation failed[\s\S]*validation result missing'
Assert-Contains -Name "workspace review prints sync hygiene gate" -Text $workspace -Pattern 'function\s+Write-WorkspaceTaskReview[\s\S]*Get-WorkspaceTaskSyncHygieneStatus[\s\S]*Confirm sync hygiene before review[\s\S]*Review should not accept the task until sync hygiene is reviewed'
Assert-Contains -Name "workspace review withholds acceptance until gate passes" -Text $workspace -Pattern 'if\s*\(\$reviewDecision\.Verdict\s+-eq\s+"validation passed"\)[\s\S]*accept:\s+adp workspace task mark \$\(\$Task\.name\) reviewed[\s\S]*accept:\s+withheld until review decision gate is OK[\s\S]*Commit readiness requires sync hygiene, recorded validation'
Assert-Contains -Name "workspace rollback reads validation and sync hygiene state" -Text $workspace -Pattern 'function\s+Write-WorkspaceTaskRollback[\s\S]*Get-WorkspaceTaskSyncHygieneStatus[\s\S]*Decision context:[\s\S]*sync hygiene:[\s\S]*recorded validation:'
Assert-Contains -Name "workspace rollback withholds restore when checkpoint gate blocks" -Text $workspace -Pattern 'Snapshot rollback is not ready:[\s\S]*Resolve the checkpoint gate before using VM snapshot rollback[\s\S]*adp restore \$\(\$Task\.runtime\) \$\(\$Task\.snapshot\)'
Assert-Contains -Name "workspace rollback withholds restore when checkpoint is waived" -Text $workspace -Pattern 'Snapshot rollback is waived:[\s\S]*No VM restore command is printed because no checkpoint was confirmed[\s\S]*adp restore \$\(\$Task\.runtime\) \$\(\$Task\.snapshot\)'
Assert-Contains -Name "workspace rollback prints local rollback mark command" -Text $workspace -Pattern 'After rollback is completed manually, record local rollback state:[\s\S]*adp workspace task mark \$\(\$Task\.name\) rollback'
Assert-Contains -Name "workspace rollback receives manifest and state paths" -Text $workspace -Pattern '"rollback"\s*\{[\s\S]*Write-WorkspaceTaskRollback\s+-Manifest\s+\$Manifest\s+-Task\s+\$task\s+-ManifestPath\s+\$Path\s+-StatePath\s+\$LocalStatePath'
Assert-Contains -Name "workspace commit has readiness gate" -Text $workspace -Pattern 'function\s+Get-WorkspaceCommitDecision[\s\S]*blocked by sync hygiene[\s\S]*blocked by validation[\s\S]*commit ready[\s\S]*review not recorded'
Assert-Contains -Name "workspace commit reads validation and sync hygiene state" -Text $workspace -Pattern 'function\s+Write-WorkspaceTaskCommit[\s\S]*Get-WorkspaceTaskSyncHygieneStatus[\s\S]*Commit readiness gate:[\s\S]*sync hygiene:[\s\S]*recorded validation:'
Assert-Contains -Name "workspace commit withholds git commands until ready" -Text $workspace -Pattern 'if\s*\(\$commitDecision\.Verdict\s+-eq\s+"commit ready"\)[\s\S]*git add <paths>[\s\S]*Commit commands withheld until commit readiness is OK'
Assert-Contains -Name "workspace commit prints local committed mark command" -Text $workspace -Pattern 'After the commit is created manually, record local committed state:[\s\S]*adp workspace task mark \$\(\$Task\.name\) committed'
Assert-Contains -Name "workspace commit receives manifest and state path" -Text $workspace -Pattern '"commit"\s*\{[\s\S]*Write-WorkspaceTaskCommit\s+-Manifest\s+\$Manifest\s+-Task\s+\$task\s+-ManifestPath\s+\$Path\s+-StatePath\s+\$LocalStatePath'
Assert-Contains -Name "workspace state defaults to ignored local path" -Text $workspace -Pattern 'adp-workspace\.state\.json'
Assert-Contains -Name "workspace task mark records local state only" -Text $workspace -Pattern 'Recorded local lifecycle state only\. No VM, sync, snapshot, file, Git, or validation command was run'
Assert-Contains -Name "workspace task mark supports checkpoint waiver boundary" -Text $workspace -Pattern '\$validStates\s*=\s*@\("prepared", "checkpointed", "checkpoint-waived"[\s\S]*checkpoint-waived records explicit human acceptance of missing VM snapshot protection[\s\S]*does not create a snapshot, prove rollback safety, or restore rollback capability'
Assert-Contains -Name "workspace task lifecycle is plan-only" -Text $workspace -Pattern 'Task lifecycle output is plan-only\. No VM, sync, snapshot, file, Git, or validation command will be changed or run'
Assert-Contains -Name "workspace task run states manual execution boundary" -Text $workspace -Pattern 'Manual execution only: this command does not start an agent, approve broad agent work, record task state, run validation, or make the task commit-ready'
Assert-Contains -Name "workspace task run points running mark to local state" -Text $workspace -Pattern 'After manual execution starts, mark running only as local state:[\s\S]*adp workspace task mark \$\(\$Task\.name\) running'
Assert-Contains -Name "workspace task mark running boundary" -Text $workspace -Pattern 'running means manual execution began or was attempted; ADP-OS did not start the agent, approve execution, validate output, or satisfy review/commit readiness'
Assert-Contains -Name "workspace task mark reviewed boundary" -Text $workspace -Pattern 'reviewed should be used only after human source review accepts the diff, rollback path, snapshot context, and recorded validation evidence'
Assert-Contains -Name "workspace task mark committed boundary" -Text $workspace -Pattern 'committed is a local lifecycle note only; ADP-OS did not stage files or run git commit'
Assert-Contains -Name "workspace task mark rollback boundary" -Text $workspace -Pattern 'rollback is a local lifecycle note only; ADP-OS did not restore snapshots or modify source files'
Assert-Contains -Name "workspace task lifecycle supports prepare" -Text $workspace -Pattern '"prepare"[\s\S]*Write-WorkspaceTaskPrepare'
Assert-Contains -Name "workspace task lifecycle supports snapshot" -Text $workspace -Pattern '"snapshot"[\s\S]*Write-WorkspaceTaskSnapshot'
Assert-Contains -Name "workspace task lifecycle supports run" -Text $workspace -Pattern '"run"[\s\S]*Write-WorkspaceTaskRun'
Assert-Contains -Name "workspace task lifecycle supports validate" -Text $workspace -Pattern '"validate"[\s\S]*Write-WorkspaceTaskValidate'
Assert-Contains -Name "workspace task lifecycle supports review" -Text $workspace -Pattern '"review"[\s\S]*Write-WorkspaceTaskReview'
Assert-Contains -Name "workspace task lifecycle supports rollback" -Text $workspace -Pattern '"rollback"[\s\S]*Write-WorkspaceTaskRollback'
Assert-Contains -Name "workspace task lifecycle supports commit" -Text $workspace -Pattern '"commit"[\s\S]*Write-WorkspaceTaskCommit'
Assert-Contains -Name "workspace task lifecycle supports mark" -Text $workspace -Pattern '"mark"[\s\S]*Write-WorkspaceTaskMark'

Write-Output "CLI parameter contracts OK"
