# ADP-OS command registration helpers.
# Registers a user-level `adpos` shim without adding the repository root to PATH.

function Get-ADPOSLocalAppData {
    if ($env:LOCALAPPDATA) {
        return $env:LOCALAPPDATA
    }

    if ($env:USERPROFILE) {
        return (Join-Path $env:USERPROFILE "AppData\Local")
    }

    throw "LOCALAPPDATA and USERPROFILE are both unavailable; cannot resolve ADP-OS command directory."
}

function Get-ADPOSCommandBinPath {
    return (Join-Path (Get-ADPOSLocalAppData) "ADP-OS\bin")
}

function Get-ADPOSCommandShimPath {
    return (Join-Path (Get-ADPOSCommandBinPath) "adpos.cmd")
}

function Get-ADPOSHomeVariableName {
    return "ADPOS_HOME"
}

function Normalize-ADPOSPath {
    param([string]$Path)

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return ""
    }

    try {
        return ([System.IO.Path]::GetFullPath($Path)).TrimEnd('\', '/')
    } catch {
        return $Path.TrimEnd('\', '/')
    }
}

function Test-ADPOSPathListContains {
    param(
        [string]$PathList,
        [string]$Path
    )

    $target = Normalize-ADPOSPath -Path $Path
    foreach ($entry in (($PathList -split ';') | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })) {
        if ([string]::Equals((Normalize-ADPOSPath -Path $entry), $target, [System.StringComparison]::OrdinalIgnoreCase)) {
            return $true
        }
    }

    return $false
}

function Add-ADPOSPathEntry {
    param([string]$Path)

    $userPath = [System.Environment]::GetEnvironmentVariable("Path", "User")
    if (-not (Test-ADPOSPathListContains -PathList $userPath -Path $Path)) {
        $newUserPath = if ([string]::IsNullOrWhiteSpace($userPath)) { $Path } else { "$userPath;$Path" }
        [System.Environment]::SetEnvironmentVariable("Path", $newUserPath, "User")
    }

    if (-not (Test-ADPOSPathListContains -PathList $env:Path -Path $Path)) {
        $env:Path = if ([string]::IsNullOrWhiteSpace($env:Path)) { $Path } else { "$env:Path;$Path" }
    }
}

function Remove-ADPOSPathEntry {
    param([string]$Path)

    $target = Normalize-ADPOSPath -Path $Path
    $userPath = [System.Environment]::GetEnvironmentVariable("Path", "User")
    $keptUserEntries = @()
    foreach ($entry in (($userPath -split ';') | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })) {
        if (-not [string]::Equals((Normalize-ADPOSPath -Path $entry), $target, [System.StringComparison]::OrdinalIgnoreCase)) {
            $keptUserEntries += $entry
        }
    }
    [System.Environment]::SetEnvironmentVariable("Path", ($keptUserEntries -join ';'), "User")

    $keptProcessEntries = @()
    foreach ($entry in (($env:Path -split ';') | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })) {
        if (-not [string]::Equals((Normalize-ADPOSPath -Path $entry), $target, [System.StringComparison]::OrdinalIgnoreCase)) {
            $keptProcessEntries += $entry
        }
    }
    $env:Path = ($keptProcessEntries -join ';')
}

function Install-ADPOSCommandRegistration {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ProjectRoot
    )

    $resolvedProjectRoot = [System.IO.Path]::GetFullPath($ProjectRoot)
    $repoCommand = Join-Path $resolvedProjectRoot "adpos.cmd"
    if (-not (Test-Path -LiteralPath $repoCommand)) {
        throw "Cannot register adpos: repo-local adpos.cmd was not found at $repoCommand"
    }

    $binPath = Get-ADPOSCommandBinPath
    $shimPath = Get-ADPOSCommandShimPath
    $homeVariableName = Get-ADPOSHomeVariableName
    New-Item -ItemType Directory -Path $binPath -Force | Out-Null

    $shimLines = @(
        "@echo off",
        "REM ADP-OS global command shim. Generated by setup.cmd.",
        "setlocal",
        "if ""%ADPOS_HOME%""=="""" (",
        "    if /i ""%~1""==""uninstall"" goto ADPOS_UNINSTALL_FALLBACK",
        "    echo ADP-OS command home is not configured.",
        "    echo Re-run setup.cmd from the cloned ADP-OS repository to repair adpos.",
        "    exit /b 1",
        ")",
        "if not exist ""%ADPOS_HOME%\adpos.cmd"" (",
        "    if /i ""%~1""==""uninstall"" goto ADPOS_UNINSTALL_FALLBACK",
        "    echo ADP-OS command target not found: %ADPOS_HOME%",
        "    echo Re-run setup.cmd from the cloned ADP-OS repository to repair adpos.",
        "    exit /b 1",
        ")",
        "if /i ""%~1""==""uninstall"" (",
        "    call ""%ADPOS_HOME%\uninstall.cmd"" %*",
        "    exit /b %ERRORLEVEL%",
        ")",
        "call ""%ADPOS_HOME%\adpos.cmd"" %*",
        "exit /b %ERRORLEVEL%",
        ":ADPOS_UNINSTALL_FALLBACK",
        "set ""ADPOS_WINPS=%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe""",
        "if not exist ""%ADPOS_WINPS%"" set ""ADPOS_WINPS=powershell.exe""",
        """%ADPOS_WINPS%"" -NoProfile -ExecutionPolicy Bypass -Command ""`$bin=Join-Path `$env:LOCALAPPDATA 'ADP-OS\bin'; `$shim=Join-Path `$bin 'adpos.cmd'; if (Test-Path -LiteralPath `$shim) { Remove-Item -LiteralPath `$shim -Force }; `$path=[Environment]::GetEnvironmentVariable('Path','User'); `$new=((`$path -split ';') | Where-Object { `$_ -and ((`$_ -replace '[\\/]+$','') -ine (`$bin -replace '[\\/]+$','')) }) -join ';'; [Environment]::SetEnvironmentVariable('Path',`$new,'User'); [Environment]::SetEnvironmentVariable('ADPOS_HOME',`$null,'User')""",
        "exit /b %ERRORLEVEL%"
    )
    Set-Content -LiteralPath $shimPath -Value $shimLines -Encoding ascii

    [System.Environment]::SetEnvironmentVariable($homeVariableName, $resolvedProjectRoot, "User")
    Set-Item -Path "Env:$homeVariableName" -Value $resolvedProjectRoot
    Add-ADPOSPathEntry -Path $binPath

    return [pscustomobject]@{
        Command  = "adpos"
        BinPath  = $binPath
        ShimPath = $shimPath
        Home     = $resolvedProjectRoot
    }
}

function Uninstall-ADPOSCommandRegistration {
    $binPath = Get-ADPOSCommandBinPath
    $shimPath = Get-ADPOSCommandShimPath
    $homeVariableName = Get-ADPOSHomeVariableName
    $removedShim = $false
    $removedHome = $false

    if (Test-Path -LiteralPath $shimPath) {
        $content = Get-Content -LiteralPath $shimPath -Raw -ErrorAction SilentlyContinue
        if ($content -match "ADP-OS global command shim") {
            Remove-Item -LiteralPath $shimPath -Force
            $removedShim = $true
        } else {
            throw "Refusing to remove non-ADP file at $shimPath"
        }
    }

    Remove-ADPOSPathEntry -Path $binPath
    if ([System.Environment]::GetEnvironmentVariable($homeVariableName, "User")) {
        [System.Environment]::SetEnvironmentVariable($homeVariableName, $null, "User")
        $removedHome = $true
    }
    if (Test-Path "Env:$homeVariableName") {
        Remove-Item -Path "Env:$homeVariableName" -ErrorAction SilentlyContinue
    }

    if ((Test-Path -LiteralPath $binPath) -and -not (Get-ChildItem -LiteralPath $binPath -Force | Select-Object -First 1)) {
        Remove-Item -LiteralPath $binPath -Force
    }

    return [pscustomobject]@{
        Command     = "adpos"
        BinPath     = $binPath
        ShimPath    = $shimPath
        RemovedShim = $removedShim
        RemovedHome = $removedHome
    }
}
